### ISSUE TITLE
FieldNamesChecker thinks local vals are fields.

### ISSUE THREAD

**Issue by iphydf** [scalastyle/scalastyle#149] opened 2015-06-15 23:56 UTC
It thinks that `(` is a field name and errors out.

```
object Foo {
  def foo(): Unit = {
    // Field name does not match the regular expression '[a-z][A-Za-z]*'
    val (thingOne, thingTwo) = (3, 4)
  }
}
```

**Comment by matthewfarwell** [comment] 2017-04-17 11:53
Closed. Duplicate of #199

**Closed by matthewfarwell** 2017-04-17 11:53 UTC
Labels: bug
