### ISSUE TITLE
MethodLengthChecker interprets maxLength differently, depending on ignoreComments

### ISSUE THREAD

**Issue by Darhazer** [scalastyle/scalastyle#302] opened 2018-02-27 15:54 UTC
I was working on adding the ignoreEmptyLines option (see #300). Unlike #301 I decided to do some refactoring to make the code more functional. The existing tests won't pass.
After some debugging, I found that the problem is actually in the existing code base, which have an off-by-one error.

See:
```scala
@Test def testOK(): Unit = {
  val source = """
package foobar

class F1() {
  def method1() = {
    def foobar() = { 5 }
    2
    3
    4
    5
    6
    7
  }
}
"""

  assertErrors(List(columnError(5, 6, List("7"))), source, Map("maxLength" -> "7", "ignoreComments" -> "false")) // PASS
}
```

same code, this time with ignoreComments:
```scala
@Test def testOK(): Unit = {
  val source = """
package foobar

class F1() {
  def method1() = {
    def foobar() = { 5 }
    2
    3
    4
    5
    6
    7
  }
}
"""

  assertErrors(List(columnError(5, 6, List("7"))), source, Map("maxLength" -> "7", "ignoreComments" -> "true")) // FAIL
  }
```

With ignoreComments, the check allows for max 8 lines
Without ignoreComments, the check allows for max 6 lines

For the record, [my version](https://github.com/scalastyle/scalastyle/compare/master...Darhazer:refactor-method-length-checker?expand=1) and a [more functional one](https://github.com/scalastyle/scalastyle/compare/master...Darhazer:immutable-method-length-checker?expand=1)

**Comment by canoztokmak** [comment] 2018-02-27 16:15
Hey @Darhazer,

In PR #301 , I realized that issue and fixed it already. After that one is merged, this bug will disappear.

**Comment by Darhazer** [comment] 2018-03-06 12:58
There's one more issue - since it uses `contains` to check if the string is in multiline comment, it skips lines that end with `/*`, although the line itself contains valid code

**Comment by canoztokmak** [comment] 2018-03-06 15:12
I thought that was an implementation decision since the issue is already pointed out in the code as comment.

https://github.com/scalastyle/scalastyle/blob/b3c6c80e31d4d557c10c70ec19821c48bf3e05af/src/main/scala/org/scalastyle/scalariform/MethodLengthChecker.scala#L83

**Comment by canoztokmak** [comment] 2018-03-17 23:26
can be closed since pr is merged..

**Comment by matthewfarwell** [comment] 2018-03-18 08:19
Fixed by #301.

**Closed by matthewfarwell** 2018-03-18 08:19 UTC
