### ISSUE TITLE
Inner method triggers 'public method must have explicit type'

### ISSUE THREAD

**Issue by joost-de-vries** [scalastyle/scalastyle#85] opened 2014-02-21 08:00 UTC
```scala
def outerMethod():String={
  def innerMethod()="foo"
  "bar"
}
```  
gets a warning that `innerMethod` is a public method that needs an explicit type.
I'd argue that innerMethod is not public.

**Comment by matthewfarwell** [comment] 2015-01-07 23:05
In fact the second part is a duplicate of #33 so I'm now closing this issue.

**Closed by matthewfarwell** 2015-01-07 23:05 UTC
Labels: bug
