### ISSUE TITLE
support for sbt 1.0?

### ISSUE THREAD

**Issue by SethTisue** [scalastyle/scalastyle#271] opened 2017-08-14 19:48 UTC
it would be nice if the sbt plugin were available for sbt 1.0

**Comment by matthewfarwell** [comment] 2017-08-14 20:09
Duplicate of https://github.com/scalastyle/scalastyle-sbt-plugin/issues/62

**Comment by matthewfarwell** [comment] 2017-08-14 20:10
Will be releasing in the next couple of days.

**Comment by matthewfarwell** [comment] 2017-08-20 21:21
Fixed and released actually.

**Closed by matthewfarwell** 2017-08-20 21:21 UTC
